container_commands:
  00_node_binary:
    command: 'ln -sf `ls -td /opt/elasticbeanstalk/node-install/node-* | head -1`/bin/node /bin/node'
  00_npm_binary:
    command: 'ln -sf `ls -td /opt/elasticbeanstalk/node-install/node-* | head -1`/bin/npm /bin/npm'
  50-run-database-migrations:
    command: './node_modules/.bin/sequelize-cli db:migrate'
    leader_only: true